#
# Makefile for the linux kernel.
#

obj-y					:= core.o clock.o
obj-$(CONFIG_LF1000_GPIO)		+= gpio_main.o gpio.o
obj-$(CONFIG_ARCH_LF1000)		+= lf1000_core_func.o
obj-$(CONFIG_ARCH_LF1000)		+= lf1000.o
