#
# Makefile for the kernel LF1000 device drivers.
#

# Object files in subdirectories

CFLAGS	+=-D WITH_PROCFS

obj-$(CONFIG_LF1000_ADC)	+= adc/
obj-$(CONFIG_LF1000_PWM)	+= pwm/
obj-$(CONFIG_LF1000_GA3D)	+= ga3d/
obj-$(CONFIG_LF1000_DMA)	+= dma/
obj-$(CONFIG_LF1000_DMATEST)	+= dmatest/
obj-$(CONFIG_LF1000_OSS)	+= i2s/
obj-$(CONFIG_LF1000_SPI)	+= spi/
obj-$(CONFIG_LF1000_MLC)	+= mlc/
obj-$(CONFIG_LF1000_DPC)	+= dpc/
obj-$(CONFIG_LF1000_IDCT)	+= idct/
